hide_download: true
hide_download_original: null
leftnav:
- identifier: 0cf97774-3630-9b77-1449-fce7bdcce18d
  name: Syllabus
  pageRef: /pages/syllabus
  weight: 10
- identifier: 45afe4dd-1028-b370-38f8-fe50e0356c4b
  name: Instructor Insights
  pageRef: /pages/instructor-insights
  weight: 20
- identifier: 2bfbd890-64f8-23e6-b295-ecde160ce342
  name: Lecture Notes
  pageRef: /pages/lecture-notes
  weight: 30
- identifier: decf8e96-9870-4a57-44f9-3ef9ff09496f
  name: Assignments
  pageRef: /pages/assignments
  weight: 40
